version: "3.7"

services:
  nginx_app:
    image: nginx:latest
    depends_on:
      - flask_app
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080
    networks:
      - my_project_network

  flask_app :
    build:
      context: .
      dockerfile: Dockerfile

    networks:
      - my_project_network

  

networks:
  my_project_network:
    external: true